### ISSUE TITLE
Trackback error

### ISSUE THREAD

**Issue by ofilipelopes** [leandertolksdorf/1001-tracklists-api#14]
I having this problem:

Traceback (most recent call last):
  File "C:\Users\filip\1001tracklist\1001-tracklists-api\home.py", line 7, in <module>
    t1 = Tracklist(url)
         ^^^^^^^^^^^^^^
  File "C:\Users\filip\1001tracklist\1001-tracklists-api\tracklists\tracklists.py", line 62, in __init__
    self.fetch()
  File "C:\Users\filip\1001tracklist\1001-tracklists-api\tracklists\tracklists.py", line 69, in fetch
    self.load_metadata(left_pane)
  File "C:\Users\filip\1001tracklist\1001-tracklists-api\tracklists\tracklists.py", line 99, in load_metadata
    for interaction_detail in left_pane.find_all("meta", itemprop="interactionCount"):
                              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by mrlopezco** [comment]
Same issue here

**Comment by ofilipelopes** [comment]
u fixed it?

**Comment by Lirry18** [comment]
Seems like the url doesnt return the site you see in the browser. Thats why all the things you search for with BeautifulSoup return nothing. Looking in to why that is

**Comment by ghost** [comment]
Can somebody fix this?
I want to use it but I don't know anything about python :(
